### ISSUE TITLE
Wolfenstein 3D - All PC versions - ECWolf ; Outdated ECWolf

### ISSUE THREAD

**Issue by Rathmox** [legluondunet/MyLittleLutrisScripts#160] opened 2024-02-18 18:51 UTC
In the Wolfenstein 3D - All PC versions - ECWolf script,
The Wolfenstein 3D tarball is outdated.

btw why do you ship ECWolf independently from the original dev ?

**Comment by legluondunet** [comment] 2024-02-18 19:24
Hello again, does it work on your computer? Why do you need an update?

> btw why do you ship ECWolf independently from the original dev ?

because ECWolf dev did not provide binary releases when I wrote this script.

**Comment by Rathmox** [comment] 2024-02-18 20:35
ECWolf 1.4.1 released which adds a lot of improvements: https://maniacsvault.net/
And personnally I prefer playing on latest versions all the time. But indeed, at the end it does not prevent playing.

And I don't know if you can extract .deb with a lutris scripts but files are downloadable: https://debian.drdteam.org/pool/multiverse/e/ecwolf/
Of course we can't make the script update automatically and it would requiere the user to input the file and seeing your guidelines in how you make your scripts it may not work.
At the end, the issue I see when you redistribute content is that it's hard for you to follow all updates. But as I said, it depends on how you want to make them

**Comment by legluondunet** [comment] 2024-02-19 01:35
I just updated ECWolf to latest version. Could you reinstall the game and tell me if it works for you. What Linux distribution name and version do you use?

**Comment by legluondunet** [comment] 2024-02-19 11:33
Good news.
> btw do you think you can make a version the supports GOG installer ?
This script supports all WFS3D PC install.
For GOG you have first to install it somewhere with Wine, then launch the script to select install folder.

**Comment by Rathmox** [comment] 2024-02-19 17:12
> For GOG you have first to install it somewhere with Wine, then launch the Lutris script to select install folder.
that's why I asked, I saw scripts from you (for RTCW) that auto install from gog and copy files.
But I know how to set it up

**Comment by legluondunet** [comment] 2024-02-19 19:08
The problem is I don't own this game on GOG, so it is difficult for me to write a script installer without possibility to test it.

**Comment by Rathmox** [comment] 2024-02-19 21:39
oh, ok

**Comment by legluondunet** [comment] 2024-02-19 22:24
Finally I wrote two scripts: one for Steam and another for GOG.
Tell me if the GOG script works for  you. If so, you could close this issue.

**Comment by Rathmox** [comment] 2024-02-20 00:20
The GOG script for Wolfenstein 3D Works.
But the one for Spear of Destiny does not: it looks like it's the same from Wolfenstein 3D.
All the files for Spear of Destiny are contained in one folder named `m1`, just past the root of the game install.
And for some reason, Lutris does not match Wonfenstein 3D from Lutris DB and from GOG.

also, ECWolf prompts to choose between Wolfenstein 3D and Spear of Destiny when it finds both of them, do you think you can make a 2 in 1 script (as both games are shipped together on Steam and GOG)

**Comment by legluondunet** [comment] 2024-02-20 03:50
> All the files for Spear of Destiny are contained in one folder named m1, just past the root of the game install.

fixed!
> And for some reason, Lutris does not match Wonfenstein 3D from Lutris DB and from GOG.

fixed!
> do you think you can make a 2 in 1 script (as both games are shipped together on Steam and GOG)

I prefer to keep them separated.

It's a pity GOG provides only "Spear of Destiny" episode 1, Steam provides all 3 episodes.

**Comment by legluondunet** [comment] 2024-02-20 20:43
> I think it went the same for Steam but because you may have bought it before, you could still keep it.

It's indeed possible, I bought these games on Steam a long time ago

We can now close this issue, thank you for your contribution, it was very constructive.

**Closed by legluondunet** 2024-02-20 20:43 UTC
Labels: script request, needs_update, wolfenstein3d

**Comment by Rathmox** [comment] 2024-02-20 22:15
You're welcome
