### ISSUE TITLE
Can't seem to install Genshin Impact

### ISSUE THREAD

**Issue by ggtylerr** [legluondunet/MyLittleLutrisScripts#120] opened 2022-02-22 05:56 UTC
Hi there. I'm trying to install the game, but whenever I go to do so, it shows up as this:
![image](https://user-images.githubusercontent.com/28498877/154998304-9639a9e0-7621-4eec-9878-cca0db9b8fb2.png)

I've left this screen on for over 12 hours and it still doesn't work. Not sure if there's a window I'm supposed to see or something, but nothing ever pops up, and this screen always stays like this. Closing it results in the installer thinking it's a success, but applying the patch says it can't find the game files. Running the game just shows the GI image and nothing else.

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/8113978/lutris.log)
uname -a - `Linux pop-os 5.15.15-76051515-generic #202201160435~1642693824~20.04~97db1bb-Ubuntu SMP Fri Jan 21 14: x86_64 x86_64 x86_64 GNU/Linux`
lsb_release -a - 
```
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by legluondunet** [comment] 2022-02-22 06:12
Hello, thank you for your report.
Please launch Lutris in a terminal in debug mode:
lutris -d
then try again to install Genshin Impact.
You must have latest Lutris client version installed 0.5.10
Then copy paste terminal log here.

**Comment by ggtylerr** [comment] 2022-02-22 09:12
Sorry the late-ish response. Using Lutris 0.5.10-beta1 showed up with [this log.](https://github.com/legluondunet/MyLittleLutrisScripts/files/8115225/lutris-0.5.10-beta1.terminal.log) (copy-pasted terminal output to a file so this page isn't clogged)

First try lead to an error code of 256. _(line 160)_ Cancelling and trying again eventually lead to a black screen on Wine's desktop:
![image](https://user-images.githubusercontent.com/28498877/155099999-c86d5856-4c8f-4737-b79f-c032f8e199c6.png)

**Comment by legluondunet** [comment] 2022-02-25 10:24
try this, rename this folder:
close lutris
/home/ggtylerr/.local/share/lutris/runtime
in
/home/ggtylerr/.local/share/lutris/runtime.bak

in Lutris wine preferences, be sure to use more recent wine version by default:

![Peek 25-02-2022 11-23](https://user-images.githubusercontent.com/325405/155698834-0804a19c-4745-4d33-9897-e0bf10f7bf0c.gif)

reopen lutris and try again to launch gi install script

**Comment by mtdb** [comment] 2022-02-27 14:36
same issue, I solved it by coping the `/Program Files/Genshin Impact` folder from a windows installation, after that the patch process worked fine

**Comment by ggtylerr** [comment] 2022-02-28 17:52
@legluondunet Already was using lutris-fshack-7.1. [Here's the log file for that.](https://github.com/legluondunet/MyLittleLutrisScripts/files/8155511/lutris-fshack-7.1.log)
I tried running WineHQ Staging (7.1 Staging) and that didn't work either. [Log file.](https://github.com/legluondunet/MyLittleLutrisScripts/files/8155526/wine-7.1-staging.log)

@mtdb I switched to Linux cause the hard drive I have Windows on is dying, so sadly I can't do the same thing :( I might just result to using a VM.

**Comment by Samega7Cattac** [comment] 2022-03-10 19:25
I have the same issue, black screen during install.
The 256 error, just delete the game folder, it seems to be bc installing on top on the folder u tried to install unsuccessfully.

**Comment by legluondunet** [comment] 2022-03-26 08:51
Hello @ggtylerr @mtdb @tommyvct @Samega7Cattac , I just updated GI Lutris script (256 error fixed!).
Could you try it and tell me if it fixes your issue?

**Comment by legluondunet** [comment] 2022-04-01 09:32
no answer, I just tested again this script installer and I can not reproduce any issue, so I close this issue.

**Closed by legluondunet** 2022-04-01 09:32 UTC
Labels: bug, gi

**Comment by huntears** [comment] 2022-08-23 08:26
Well I can say that I have the same problem, a black screen during the installation and then I get stuck on the launch screen afterwards like previously reported.
I'll get logs a bit later today.
